# Generated by Django 5.2.6 on 2025-09-11 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApoioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipe/')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistaDeRua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('redes_sociais', models.CharField(blank=True, max_length=200)),
                ('biografia', models.TextField(blank=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidade')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estiloarte')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.artistaderua')),
            ],
        ),
        migrations.CreateModel(
            name='IntervencaoArtistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da intervenção (formato JPG ou PNG)', null=True, upload_to='intervencoes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('visivel', models.BooleanField(default=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.artistaderua')),
            ],
        ),
        migrations.CreateModel(
            name='LocalArtistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidade')),
            ],
        ),
    ]
