# Generated by Django 5.2.4 on 2025-07-07 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Gênero')),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do leitor')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do leitor')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF do leitor')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do autor')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidade', verbose_name='Cidade do autor')),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da editora')),
                ('site', models.CharField(max_length=100, verbose_name='Site da editora')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidade', verbose_name='Cidade da editora')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do livro')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço do livro')),
                ('data_pub', models.DateField(verbose_name='Data de publicação')),
                ('status', models.BooleanField(verbose_name='Disponível?')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor', verbose_name='Autor do livro')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editora', verbose_name='Editora do livro')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genero', verbose_name='Gênero do livro')),
            ],
        ),
    ]
