# Generated by Django 5.2.4 on 2025-07-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistaDeRua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('redes_sociais', models.CharField(blank=True, max_length=200)),
                ('biografia', models.TextField(blank=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidade')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estiloarte')),
            ],
        ),
        migrations.CreateModel(
            name='IntervencaoArtistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('imagem', models.URLField(blank=True, help_text='Link para imagem da intervenção')),
                ('visivel', models.BooleanField(default=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.artistaderua')),
            ],
        ),
    ]
