# Generated by Django 5.2.4 on 2025-07-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistaDeRua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('redes_sociais', models.CharField(blank=True, max_length=200)),
                ('biografia', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipodeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IntervencaoArtistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('imagem', models.URLField(blank=True, help_text='Link para imagem da intervenção')),
                ('visivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='autor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='editora',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Leitor',
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='artistaderua',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cidade'),
        ),
        migrations.AddField(
            model_name='artistaderua',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estiloarte'),
        ),
        migrations.AddField(
            model_name='intervencaoartistica',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.artistaderua'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
