# Generated by Django 5.2.4 on 2025-07-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_artistaderua_estiloarte_intervencaoartistica_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipodeEvento',
            new_name='EstiloArte',
        ),
    ]
